# Generated by Django 4.1.7 on 2023-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True, verbose_name='이름')),
                ('password', models.CharField(max_length=50, null=True, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='비밀번호')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='비밀번호')),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='userimage/', verbose_name='유저사진')),
                ('usermemo', models.TextField(verbose_name='유저소개')),
            ],
        ),
    ]
