# Generated by Django 4.1.7 on 2023-04-17 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budgetcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='수입지출제목')),
                ('kind', models.BooleanField(default=True, verbose_name='종류')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='액수')),
                ('memo', models.TextField(verbose_name='수입지출메모')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorybudgetfor', to='calendars.budgetcategory')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBugetFor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
