# Generated by Django 4.1.7 on 2023-04-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='게시글제목')),
                ('context', models.TextField(verbose_name='수입지출메모')),
                ('date', models.TextField(blank=True, default='null', null=True, verbose_name='저장날짜')),
                ('boardimage', models.ImageField(blank=True, null=True, upload_to='boardimage/', verbose_name='게시글사진')),
            ],
        ),
        migrations.CreateModel(
            name='Boardcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Boardcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='댓글내용')),
                ('date', models.TextField(blank=True, default='null', null=True, verbose_name='저장날짜')),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardCommentFor', to='boards.board')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCommentFor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryBoardFor', to='boards.boardcategory'),
        ),
        migrations.AddField(
            model_name='board',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBoardFor', to=settings.AUTH_USER_MODEL),
        ),
    ]
