# Generated by Django 4.1.7 on 2023-04-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='context',
            field=models.TextField(verbose_name='본문'),
        ),
    ]
